version: '2'

services:
  django:
    build: ./django
    volumes:
      - ./django:/webapp
    depends_on:
      - celery
      - node
      - db
    ports:
      - "8000:8000"

  celery:
    build: ./django
    command: celery worker -A Observium -l info
    volumes:
      - ./django:/webapp
    depends_on:
      - redis

  node:
    build: ./node
    volumes:
      - ./node:/nodeapp
    depends_on:
      - redis
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - django

  redis:
    image: redis

  db:
     image: mysql:5.6.40
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: scopedge
       MYSQL_DATABASE: ObserviumDB

volumes:
    dbdata:
